import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Sparkles, Target, TrendingUp, ArrowRight, CheckCircle2, Zap, Award } from "lucide-react";

const Home = () => {
  const navigate = useNavigate();

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Questions",
      description: "Get role-specific technical questions generated by advanced LLMs like GROQ and OpenAI",
    },
    {
      icon: Target,
      title: "Real Interview Practice",
      description: "Practice with questions similar to FAANG interviews tailored to your target role",
    },
    {
      icon: TrendingUp,
      title: "Detailed Feedback",
      description: "Receive comprehensive evaluation with strengths, weaknesses, and improvement suggestions",
    },
    {
      icon: Award,
      title: "Performance Tracking",
      description: "Track your progress with detailed summaries and performance metrics",
    },
  ];

  const benefits = [
    "Personalized interview questions based on your target role",
    "Instant AI-powered feedback on your answers",
    "Comprehensive performance analytics and summaries",
    "Practice anytime, anywhere at your own pace",
    "Improve communication and technical skills simultaneously",
  ];

  const howItWorks = [
    {
      step: 1,
      title: "Enter Your Role",
      description: "Specify your target position (e.g., Amazon SDE2, Google SWE)",
    },
    {
      step: 2,
      title: "Answer Questions",
      description: "Respond to AI-generated technical interview questions",
    },
    {
      step: 3,
      title: "Get Feedback",
      description: "Receive detailed AI feedback with scoring and suggestions",
    },
    {
      step: 4,
      title: "Review Summary",
      description: "Analyze your performance with comprehensive reports",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-subtle">
      <div className="container mx-auto px-4 py-16">
        <div className="mx-auto max-w-6xl space-y-20">
          {/* Hero Section */}
          <div className="text-center animate-in fade-in-50 duration-700">
            <div className="mb-6 flex justify-center">
              <div className="flex h-24 w-24 items-center justify-center rounded-3xl bg-gradient-primary shadow-glow">
                <Brain className="h-12 w-12 text-primary-foreground" />
              </div>
            </div>
            <h1 className="mb-6 text-6xl font-bold tracking-tight text-foreground">
              PrepMate AI
            </h1>
            <p className="mx-auto mb-4 max-w-3xl text-2xl text-muted-foreground">
              Your AI-Powered Interview Preparation Platform
            </p>
            <p className="mx-auto max-w-2xl text-lg text-muted-foreground mb-8">
              Generate role-specific technical interview questions powered by Large Language Models.
              Practice, improve, and ace your next FAANG interview with personalized AI feedback.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                onClick={() => navigate("/get-started")}
                size="lg"
                className="h-14 px-8 text-lg font-semibold shadow-lg hover:shadow-xl transition-all"
              >
                <Sparkles className="mr-2 h-5 w-5" />
                Get Started Now
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button
                onClick={() => navigate("/interview")}
                size="lg"
                variant="outline"
                className="h-14 px-8 text-lg font-semibold"
              >
                Continue Interview
              </Button>
            </div>
          </div>

          {/* Features Grid */}
          <div className="animate-in fade-in-50 duration-700 delay-100">
            <h2 className="mb-8 text-center text-3xl font-bold text-foreground">
              Why Choose PrepMate AI?
            </h2>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
              {features.map((feature, index) => (
                <Card key={index} className="border-2 hover:shadow-lg transition-all duration-300 hover:scale-105">
                  <CardHeader>
                    <div className="mb-3 flex h-14 w-14 items-center justify-center rounded-xl bg-gradient-primary">
                      <feature.icon className="h-7 w-7 text-primary-foreground" />
                    </div>
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* How It Works */}
          <div className="animate-in fade-in-50 duration-700 delay-200">
            <h2 className="mb-12 text-center text-3xl font-bold text-foreground">
              How It Works
            </h2>
            <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
              {howItWorks.map((item, index) => (
                <div key={index} className="relative text-center">
                  <div className="mb-4 flex justify-center">
                    <div className="flex h-16 w-16 items-center justify-center rounded-full bg-gradient-primary text-2xl font-bold text-primary-foreground shadow-lg">
                      {item.step}
                    </div>
                  </div>
                  <h3 className="mb-2 text-xl font-semibold text-foreground">
                    {item.title}
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    {item.description}
                  </p>
                  {index < howItWorks.length - 1 && (
                    <div className="absolute -right-4 top-8 hidden lg:block">
                      <ArrowRight className="h-6 w-6 text-muted-foreground" />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Benefits Section */}
          <div className="animate-in fade-in-50 duration-700 delay-300">
            <Card className="border-2 shadow-lg">
              <CardHeader className="text-center">
                <CardTitle className="text-3xl font-bold">
                  <Zap className="inline-block mr-2 h-8 w-8 text-primary" />
                  What You'll Get
                </CardTitle>
                <CardDescription className="text-base">
                  Everything you need to ace your technical interviews
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 md:grid-cols-2">
                  {benefits.map((benefit, index) => (
                    <div key={index} className="flex items-start gap-3">
                      <CheckCircle2 className="h-6 w-6 flex-shrink-0 text-success mt-0.5" />
                      <p className="text-foreground">{benefit}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Call to Action */}
          <div className="animate-in fade-in-50 duration-700 delay-400 text-center">
            <Card className="border-2 shadow-xl bg-gradient-to-br from-primary/5 to-accent/5">
              <CardHeader>
                <CardTitle className="text-3xl font-bold text-foreground">
                  Ready to Ace Your Next Interview?
                </CardTitle>
                <CardDescription className="text-lg">
                  Start your AI-powered interview preparation journey today
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Button
                  onClick={() => navigate("/get-started")}
                  size="lg"
                  className="h-14 px-12 text-lg font-semibold shadow-lg hover:shadow-xl transition-all"
                >
                  <Sparkles className="mr-2 h-5 w-5" />
                  Start Practicing Now
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
